type TTuningTemplate = {
  name: string,
  raised: boolean
  offset: number
  id: string
}

export const BASE_TUNING_TEMPLATES: {
  [key: string]: {
    [key: number]: TTuningTemplate[]
  }
} = {
  guitar: {
    6: [
      {
        id: '',
        name: 'A',
        raised: true,
        offset: 0,
      }, {
        id: '',
        name: 'G#/Ab',
        raised: true,
        offset: 1
      }, {
        id: '',
        name: 'G',
        raised: true,
        offset: 2
      }, {
        id: '',
        name: 'F#/Gb',
        raised: true,
        offset: 3
      }, {
        id: '',
        name: 'F',
        raised: true,
        offset: 4
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 3
      }, {
        id: 'G6C4',
        name: 'C',
        raised: false,
        offset: 4
      }, {
        id: 'G6B5',
        name: 'B',
        raised: false,
        offset: 5
      }, {
        id: 'G6A#/Bb6',
        name: 'A#/Bb',
        raised: false,
        offset: 6
      }, {
        id: 'G6A7',
        name: 'A',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 9
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 12
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 13
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 14
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 15
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 16
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 17
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 18
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 19
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 20
      },
    ],
    7: [
      {
        id: '',
        name: 'E',
        raised: true,
        offset: 0
      }, {
        id: '',
        name: 'D#/Eb',
        raised: true,
        offset: 1
      }, {
        id: '',
        name: 'D',
        raised: true,
        offset: 2
      }, {
        id: '',
        name: 'C#/Db',
        raised: true,
        offset: 3
      }, {
        id: '',
        name: 'C',
        raised: true,
        offset: 4
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 3
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 4
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 5
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 6
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 9
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 12
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 13
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 14
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 15
      },
    ],
    8: [
      {
        id: '',
        name: 'B',
        raised: true,
        offset: 0
      }, {
        id: '',
        name: 'A#/Bb',
        raised: true,
        offset: 1
      }, {
        id: '',
        name: 'A',
        raised: true,
        offset: 2
      }, {
        id: '',
        name: 'G#/Ab',
        raised: true,
        offset: 3
      }, {
        id: '',
        name: 'G',
        raised: true,
        offset: 4
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 3
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 4
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 5
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 6
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 9
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 12
      },
    ],
    9: [
      {
        id: '',
        name: 'F#/Gb',
        raised: true,
        offset: 0
      }, {
        id: '',
        name: 'F',
        raised: true,
        offset: 1
      }, {
        id: '',
        name: 'E',
        raised: true,
        offset: 2
      }, {
        id: '',
        name: 'D#/Eb',
        raised: true,
        offset: 3
      }, {
        id: '',
        name: 'D',
        raised: true,
        offset: 4
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 3
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 4
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 5
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 6
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 9
      },
    ],
    10: [
      {
        id: '',
        name: 'C#/Db',
        raised: true,
        offset: 0
      }, {
        id: '',
        name: 'C',
        raised: true,
        offset: 1
      }, {
        id: '',
        name: 'B',
        raised: true,
        offset: 2
      }, {
        id: '',
        name: 'A#/Bb',
        raised: true,
        offset: 3
      }, {
        id: '',
        name: 'A',
        raised: true,
        offset: 4
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 3
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 4
      },
    ],
  },
  bass: {
    4: [
      {
        id: '',
        name: 'E',
        raised: false,
        offset: 15
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 16
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 17
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 18
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 19
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 20
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 21
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 22
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 23
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 24
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 25
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 26
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 27
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 28
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 29
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 30
      },
    ],
    5: [
      {
        id: '',
        name: 'E',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 12
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 13
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 14
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 15
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 16
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 17
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 18
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 19
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 20
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 21
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 22
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 23
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 24
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 25
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 26
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 27
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 28
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 29
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 30
      },
    ],
    6: [
      {
        id: '',
        name: 'E',
        raised: false,
        offset: 5
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 6
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 9
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 12
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 13
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 14
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 15
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 16
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 17
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 18
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 19
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 20
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 21
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 22
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 23
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 24
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 25
      },
    ],
    7: [
      {
        id: '',
        name: 'E',
        raised: false,
        offset: 0
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 1
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 2
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 3
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 4
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 5
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 6
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 7
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 8
      }, {
        id: '',
        name: 'G',
        raised: false,
        offset: 9
      }, {
        id: '',
        name: 'F#/Gb',
        raised: false,
        offset: 10
      }, {
        id: '',
        name: 'F',
        raised: false,
        offset: 11
      }, {
        id: '',
        name: 'E',
        raised: false,
        offset: 12
      }, {
        id: '',
        name: 'D#/Eb',
        raised: false,
        offset: 13
      }, {
        id: '',
        name: 'D',
        raised: false,
        offset: 14
      }, {
        id: '',
        name: 'C#/Db',
        raised: false,
        offset: 15
      }, {
        id: '',
        name: 'C',
        raised: false,
        offset: 16
      }, {
        id: '',
        name: 'B',
        raised: false,
        offset: 17
      }, {
        id: '',
        name: 'A#/Bb',
        raised: false,
        offset: 18
      }, {
        id: '',
        name: 'A',
        raised: false,
        offset: 19
      }, {
        id: '',
        name: 'G#/Ab',
        raised: false,
        offset: 20
      },
    ],
  }
}


function createTuningTemplates() {
  const TUNING_TEMPLATES = { ...BASE_TUNING_TEMPLATES }
  Object.keys(TUNING_TEMPLATES).forEach(j => {
    Object.keys(TUNING_TEMPLATES[j]).forEach(k => {
      TUNING_TEMPLATES[j][+k].forEach(template => {
        const instrumentInitial = j === 'guitar' ? 'G' : 'B'
        template.id = `${instrumentInitial}${k}${template.name}${template.offset}`
      })
    })
  })
  return TUNING_TEMPLATES
}

export const TUNING_TEMPLATES = createTuningTemplates()
